# sourcing necessary files
source("R/run_model.R")
Rcpp::sourceCpp("src/assign_hh.cpp")
Rcpp::sourceCpp("src/create_pop_w_households.cpp")
Rcpp::sourceCpp("src/determine_initial_states.cpp")
Rcpp::sourceCpp("src/get_total_community_contacts.cpp")
Rcpp::sourceCpp("src/get_contacts_2.cpp")
Rcpp::sourceCpp("src/vaccinate.cpp")
Rcpp::sourceCpp("src/helpers.cpp")
Rcpp::sourceCpp("src/make_contacts.cpp")
Rcpp::sourceCpp("src/change_states.cpp")
Rcpp::sourceCpp("src/run_transmission_process.cpp")
