# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assign_hh <- function(pop_size, hh_info_mat) {
    .Call(`_vacamole_assign_hh`, pop_size, hh_info_mat)
}

change_states <- function(id, state_i, age_i, time_of_infection_i, latent_period_i, infectious_period_i, vac_mech, vac_status_i, ve, time_step, prop_asympt_vec, prop_severe, prop_hosp, prop_non_hosp_death, prop_hosp_death, prop_ICU, prop_ICU_death, hh_i_members, household_isolation, time_in_hh_isolation, time_sympt_to_hosp_i, time_hosp_to_discharge_i, time_hosp_to_death_i, time_hosp_to_ICU_i, time_ICU_to_hosp_i, time_ICU_step_down_care_i) {
    .Call(`_vacamole_change_states`, id, state_i, age_i, time_of_infection_i, latent_period_i, infectious_period_i, vac_mech, vac_status_i, ve, time_step, prop_asympt_vec, prop_severe, prop_hosp, prop_non_hosp_death, prop_hosp_death, prop_ICU, prop_ICU_death, hh_i_members, household_isolation, time_in_hh_isolation, time_sympt_to_hosp_i, time_hosp_to_discharge_i, time_hosp_to_death_i, time_hosp_to_ICU_i, time_ICU_to_hosp_i, time_ICU_step_down_care_i)
}

create_pop_w_households <- function(pop_size, age_dist, hh_info, n_postcodes, perc_high_risk, perc_vac_hesitant) {
    .Call(`_vacamole_create_pop_w_households`, pop_size, age_dist, hh_info, n_postcodes, perc_high_risk, perc_vac_hesitant)
}

determine_intitial_states <- function(ages, prop_inf, prop_rec) {
    .Call(`_vacamole_determine_intitial_states`, ages, prop_inf, prop_rec)
}

get_contacts <- function(contact_mat, ids, hh_ids, ages, postcodes, prop_contacts_within_postcode, household_isolation) {
    .Call(`_vacamole_get_contacts`, contact_mat, ids, hh_ids, ages, postcodes, prop_contacts_within_postcode, household_isolation)
}

get_contacts_2 <- function(contact_info, ids_to_get_contacts_for, ids, hh_ids, ages, postcodes, prop_contacts_within_postcode, household_isolation) {
    .Call(`_vacamole_get_contacts_2`, contact_info, ids_to_get_contacts_for, ids, hh_ids, ages, postcodes, prop_contacts_within_postcode, household_isolation)
}

get_total_community_contacts <- function(contact_matrix) {
    .Call(`_vacamole_get_total_community_contacts`, contact_matrix)
}

in_group <- function(x, y, id) {
    .Call(`_vacamole_in_group`, x, y, id)
}

notin_group <- function(x, y, id) {
    .Call(`_vacamole_notin_group`, x, y, id)
}

subset_vec <- function(positions, y) {
    .Call(`_vacamole_subset_vec`, positions, y)
}

my_sum <- function(x) {
    .Call(`_vacamole_my_sum`, x)
}

which_cpp <- function(x, val, type) {
    .Call(`_vacamole_which_cpp`, x, val, type)
}

rep_cpp <- function(x, y) {
    .Call(`_vacamole_rep_cpp`, x, y)
}

match_and_find <- function(x, y, z) {
    .Call(`_vacamole_match_and_find`, x, y, z)
}

make_age_prob_vec <- function(ages, probabilities) {
    .Call(`_vacamole_make_age_prob_vec`, ages, probabilities)
}

make_contacts <- function(state_i, age_i, states_c, contacts_i, age_vec, sigma, beta, vac_mech, vac_status_i, ve, tau, time_step) {
    .Call(`_vacamole_make_contacts`, state_i, age_i, states_c, contacts_i, age_vec, sigma, beta, vac_mech, vac_status_i, ve, tau, time_step)
}

vaccinate <- function(num_vaccines, ages, high_risk_status, vaccine_hesitancy, vac_status, vac_type, time_step, time_dose1, time_dose2, protection_status, time_btw_doses, time_to_protection, age_group_vac_order) {
    .Call(`_vacamole_vaccinate`, num_vaccines, ages, high_risk_status, vaccine_hesitancy, vac_status, vac_type, time_step, time_dose1, time_dose2, protection_status, time_btw_doses, time_to_protection, age_group_vac_order)
}

